version: '3.8'

services:
  gateway-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dralder-factory-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - factory-network

networks:
  factory-network:
    driver: bridge
